/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package javasurvival

import com.kotlindiscord.kord.extensions.ExtensibleBot
import com.kotlindiscord.kord.extensions.utils.loadModule
import javasurvival.extensions.*
import javasurvival.extensions.suggestions.JsonSuggestions
import javasurvival.extensions.suggestions.SuggestionsData
import javasurvival.extensions.suggestions.SuggestionsExtension
import org.koin.dsl.bind

suspend fun main() {
    val bot = ExtensibleBot(DISCORD_TOKEN) {
        chatCommands {
            enabled = true
        }

        applicationCommands {
            defaultGuild(GUILD)
        }

        extensions {
            add(::LoggingExtension)
            add(::UserExtension)
            add(::ModExtension)
            add(::PronounExtension)
            add(::ReactionRoleExtension)
            add(::SuggestionsExtension)
            add(::AutoThreadExtension)
            add(::TicketsExtension)
        }

        hooks {
            afterKoinSetup {
                val suggestions = JsonSuggestions()
                suggestions.load()

                loadModule {
                    single { suggestions } bind SuggestionsData::class
                }
            }
        }
    }

    bot.start()
}
