/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.javasurvival

import com.javasurvival.config.BotConfig
import com.javasurvival.extensions.LoggingExtension
import com.javasurvival.extensions.ModExtension
import com.javasurvival.extensions.PronounExtension
import com.javasurvival.extensions.UserExtension
import com.kotlindiscord.kord.extensions.ExtensibleBot
import com.kotlindiscord.kord.extensions.checks.inGuild
import com.kotlindiscord.kord.extensions.utils.module
import org.koin.dsl.bind

suspend fun main() {
    val config = BotConfig()

    val bot = ExtensibleBot(config.botToken) {
        messageCommands {
            check(inGuild(config.botGuild))

            defaultPrefix = "?"
        }

        slashCommands {
            check(inGuild(config.botGuild))

            enabled = true
        }

        extensions {
            // add(::TestExtension)
            add(::LoggingExtension)
            add(::UserExtension)
            add(::ModExtension)
            add(::PronounExtension)
        }

        hooks {
            afterKoinCreated {
                koin.module {
                    single { config } bind BotConfig::class
                }
            }
        }
    }

    bot.start()
}
